name: Doc

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/**'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
  repository_dispatch:
    types: [ doc ]

jobs:

  Doc:
    runs-on: ubuntu-latest
    name: 📓 Doc
    steps:

    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: 📓 Build The Docs
      uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}
        skip-deploy: github.event_name == 'pull_request'
